### PR TITLE
Build script to keep toolkit bundle file in sync with networks

### PR DESCRIPTION
**Pull request by dcwhite**
This should go in the readme for this repo:
To create the toolkit bundle file, build the latest SCIRun. A new tool called `bundle_toolkit` should be built as well. Run it to check the usage.

### CODE REVIEW

**Comment by jessdtate** [comment]
How is the test_toolkit_file.py supposed to be run, as part of travis?

**Comment by dcwhite** [comment]
Yes. It can be run locally with `pytest`, simply `pip install pytest` and run `pytest` in the same dir.

**Review by jessdtate — APPROVED** [review]
This is working for me so far.  I see that the number of networks is hard coded.  Does that mean we need to change it every time we add a network?

**Comment by dcwhite** [comment]
We can remove the 11 check and just compare the number of network files to the number of bundled networks. It would make the test failure message a bit more opaque, though.

**Comment by jessdtate** [comment]
right now the error is 'assert 12 ==11' and 'Assertionerror'.  I would prefer checking with the number of network files.

**Pull request merged**
