### PR TITLE
including missing images to manual

### PR DESCRIPTION
**Pull request by jcollfont**

### CODE REVIEW

**Review by jessdtate — COMMENTED** [review]
TikhonovSVD_module.png is missing.
All the Tikhonov images are from SR4: TikhonovNetwork.png, tik1.png,tik2.png,tik3.png

**Comment by jcollfont** [comment]
true! I didn’t realize the pictures were still old. Should be fixed now.

**Comment by jessdtate** [comment]
There is a missing image still (TikhonovSVD_module.png) did you want to add it or to remove the code for it?

**Comment by jcollfont** [comment]
Added the missing image Jess

**Review by jessdtate — APPROVED** [review]

**Pull request merged**
